### ISSUE TITLE
Add geometry of collection footprint to collection table

### ISSUE THREAD

**Issue by ctrepka** [TNRIS/data.tnris.org#15]
# TODO

- [x] Create **area_type_geometry** table containing fields **area_type_id** and **geom**
- [x] Create **collection_footprint** table containing fields **collection_id** and **geom**
- [x] Add GeoDjango filter to collections endpoint that performs ENVELOPE query on collection footprints with bbox

---------------------------------------------------------------------------------------------------------------------------------------------------

# Suggested Solutions

- For data pipeline, use combination of ST_SnapToGrid and ST_INTERSECTION to get simplified intersection of all areas related to a given collection. 
- Create collection_footprint as separate table in Django. 
- Populate existing collections using PgAdmin4. 
- Add collection_footprint.geom to collection viewtable sql.
- Add geofilter to collections viewset
- Add Django Signal to trigger lambda to generate collection_footprint.geom when a new collection is created
- Create Lamdba endpoint for above purpose
